CarDealership/CarDealarship/CarDealarship.UI/Controllers/SearchVehicleController.cs
using CarDealarship.Bll;
using CarDealarship.Model.Interface;
using CarDealarship.Model.Queries;
using CarDealarship.Model.Tables;
using CarDealarship.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Cors;

namespace CarDealarship.UI.Controllers
{
    //[EnableCors(origins: "*", headers: "*", methods: "*")]
    public class SearchVehicleController : ApiController
    {
        IVehicleRepository repo = CarFactory.Create();
        [Route("api/vehicles/featured")]
        [AcceptVerbs("GET")]
        public IHttpActionResult FeaturedVehicles()
        {
            var featured = repo.GetFeaturedVehicles();
            return Ok(featured);
        }

        [Route("api/vehicles/special")]
        [AcceptVerbs("GET")]
        public IHttpActionResult GetSpecial()
        {
            var specials = repo.GetAllSpecials();
            return Ok(specials);
        }


        [Route("api/SearchNewVehicle/SearchVehicle")]
        [AcceptVerbs("POST")]
        public IHttpActionResult SearchNewVehicle(VehicleSearchParameters pram)
        {

            pram.IsNew = true;

            var result = repo.Search(pram);

            return Ok(result);
        }


        [Route("api/SearchOdVehicle/SearchVehicle")]
        [AcceptVerbs("POST")]
        public IHttpActionResult SearchOldVehicle(VehicleSearchParameters prams)
        {

            prams.IsNew = false;

            var result = repo.SearchOldCars(prams);

            return Ok(result);
        }

        [Route("api/SearchSales/Sales")]
        [AcceptVerbs("POST")]
        public IHttpActionResult SearchSales(VehicleSearchParameters prams)
        {
            prams.IsNew = true;
            prams.IsNew = false;

            var result = repo.SearchSales(prams);
            return Ok(result);
        }

        [Route("api/Admin/Vehicle")]
        [AcceptVerbs("POST")]
        public IHttpActionResult AdminSearch(VehicleSearchParameters prams)
        {
            prams.IsNew = true;
            prams.IsNew = false;

            var result = repo.SearchSales(prams);
            return Ok(result);
        }


        [Route("api/Purchase/Sales/{id}")]
        [AcceptVerbs("POST")]
        public IHttpActionResult Purchase(SalesViewModel model)
        {
            var vehicle = repo.GetVehicleById(model.VehicleForPurchase.VehicleId);
            return Ok(vehicle);

        }


        [Route("api/SearchNewVehicle/Details/{id}")]
        [AcceptVerbs("GET")]
        public IHttpActionResult GetById(int id)
        {
            var toReturn = repo.GetVehicleById(id);
            return Ok(toReturn);
        }

        //[Route("api/Make/GetAllMakes")]
        //[AcceptVerbs("GET")]
        //public IHttpActionResult GetAllMakes()
        //{
        //    var toReturn = repo.GetAllMakes();
        //    return Ok(toReturn);
        //}

        [Route("api/Specials/GetAllSpecials")]
        [AcceptVerbs("GET")]
        public IHttpActionResult GetAllSpecials()
        {
            var specials = repo.GetAllSpecials();
            return Ok(specials);
        }



    }

}
    

CarDealership/CarDealarship/CarDealarship.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Guild Cars</title>
    
    @Styles.Render("~/Content/css")  
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Car Dealership", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("New Inventory", "SearchVehicle", "Home")</li>
                    <li>@Html.ActionLink("Useed Inventory", "SearchOldVehicle", "Home")</li>
                    <li>@Html.ActionLink("Special", "Specials", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>


                @if(User.Identity.IsAuthenticated)
                {

                   
                   if (User.IsInRole("Admin"))
                   {                       
                    
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">
                                Admin
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Vehicles", "Vehicle", "Admin")
                                </li>
                                <li>
                                    @Html.ActionLink("Add Vehicle", "AddVehicle", "Admin")
                                </li>
                                
                                <li>
                                    @Html.ActionLink("Users", "Users", "Admin")
                                </li>
                                <li>
                                    @Html.ActionLink("Add User", "AddUser", "Admin")
                                </li>
                                <li>
                                    @Html.ActionLink("Change Password ", "ChangePassword", "Manage")
                                </li>
                                <li>
                                    @Html.ActionLink("Make", "Make", "Admin")
                                </li>
                                <li>
                                    @Html.ActionLink("Models", "Modells", "Admin")
                                </li>
                                <li>
                                    @Html.ActionLink("Specials", "Specials", "Admin")
                                </li>
                            </ul>
                        </li>
                  
                    
                   }
                   if (User.IsInRole("Sales"))
                   {
                                        
                        <li>@Html.ActionLink("Sales", "Sales", "Home")</li>

                  
                   }
                }                
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/scripts/home.js")
    @Scripts.Render("~/scripts/VehicleSearch.js")
    @Scripts.Render("~/Scripts/OldVehicleSearch.js")
    @Scripts.Render("~/Scripts/SalesSearch.js")
    @Scripts.Render("~/Scripts/AdminVehicleSearch.js")
    @Scripts.Render("~/Scripts/AdminSpecials.js")
    @*@Scripts.Render("~/Scripts/MakeSearch.js")*@
   

    @RenderSection("scripts", required: false)

</body>
</html>